# Generated by Django 3.2 on 2023-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='gallery',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='club',
            name='about',
            field=models.CharField(max_length=2555),
        ),
        migrations.AlterField(
            model_name='club',
            name='motto',
            field=models.CharField(max_length=2555),
        ),
    ]
