# Generated by Django 3.2 on 2023-05-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20230525_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='about',
        ),
        migrations.RemoveField(
            model_name='club',
            name='motto',
        ),
    ]
