# Generated by Django 3.2 on 2023-05-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20230525_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophyName', models.CharField(max_length=255)),
                ('trophyYear', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
