# Generated by Django 3.2 on 2023-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='trophyImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
