# Generated by Django 3.2 on 2023-05-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20230526_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='owner',
            new_name='ownerImage',
        ),
        migrations.AddField(
            model_name='owners',
            name='ownerName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
