# Generated by Django 3.2 on 2023-05-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20230526_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('ownerName', models.CharField(max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager')], default='owner', max_length=100, null=True, verbose_name='Staff type')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['-pk'],
            },
        ),
        migrations.DeleteModel(
            name='Owners',
        ),
    ]
