# Generated by Django 3.2 on 2023-05-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_firstteam_player_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='news_type',
            field=models.CharField(choices=[('Overall', 'Overall'), ('Academy', 'Academy')], default='Overall', max_length=255),
        ),
    ]
