# Generated by Django 3.2 on 2023-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_announcement_news_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('student_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, choices=[('Goalkeepers', 'Goalkeepers'), ('Defenders', 'Defenders'), ('Midfielders', 'Midfielders'), ('Forwards', 'Forwards')], max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('under18', 'under18'), ('under15', 'under15'), ('under13', 'under13')], max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ClubStudent',
                'verbose_name_plural': 'Club Students',
                'ordering': ['-pk'],
            },
        ),
    ]
