# Generated by Django 3.2 on 2023-05-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_clubstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubstudent',
            name='student_jersey_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='clubstudent',
            name='position',
            field=models.CharField(blank=True, choices=[('Goalkeepers', 'Goalkeepers'), ('Defenders', 'Defenders'), ('Midfielders', 'Midfielders'), ('Forwards', 'Forwards'), ('CoachingStaff', 'CoachingStaff')], max_length=255, null=True),
        ),
    ]
